export const fakeSample = {
  id: "3f2504e0-4f89-41d3-9a0c-0305e82c3301",
  name: "Basalte du Massif Central",
  nature: "thin_section",
  type: null,
  material: null,
  texture: null,
  metamorphicFacies: null,
  collectionMethod: null,
  collectionMethodDescription: null,
  specificName: null,
  location: null,
  description: null,
  condition: null,
  security: null,
  scientificContext: null,
  existenceStatus: null,
  availabilityStatus: null,
  age: null,
  links: [],
  attachments: [],
  publicationYear: null,
  resourceType: null,
  economicInterestElements: [],
  economicResourceTypePrecision: null,
  economicDepositName: null,
  economicDepositDescription: null,
  igsn: null,
  status: "draft",
  createdAt: "2026-06-01T00:00:00.000Z",
  updatedAt: "2026-07-01T10:00:00.000Z",
};
