/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as SamplesCreateRouteImport } from './routes/samples.create'
import { Route as SamplesSampleIdRouteImport } from './routes/samples.$sampleId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as InstitutionalGroupsOsusIndexRouteImport } from './routes/institutional-groups.osus.index'
import { Route as InstitutionalGroupsOrganizationsIndexRouteImport } from './routes/institutional-groups.organizations.index'
import { Route as InstitutionalGroupsLaboratoriesIndexRouteImport } from './routes/institutional-groups.laboratories.index'
import { Route as InstitutionalGroupsOsusCodeRouteImport } from './routes/institutional-groups.osus.$code'
import { Route as InstitutionalGroupsOrganizationsRorRouteImport } from './routes/institutional-groups.organizations.$ror'
import { Route as InstitutionalGroupsLaboratoriesCodeRouteImport } from './routes/institutional-groups.laboratories.$code'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesCreateRoute = SamplesCreateRouteImport.update({
  id: '/samples/create',
  path: '/samples/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesSampleIdRoute = SamplesSampleIdRouteImport.update({
  id: '/samples/$sampleId',
  path: '/samples/$sampleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalGroupsOsusIndexRoute =
  InstitutionalGroupsOsusIndexRouteImport.update({
    id: '/institutional-groups/osus/',
    path: '/institutional-groups/osus/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstitutionalGroupsOrganizationsIndexRoute =
  InstitutionalGroupsOrganizationsIndexRouteImport.update({
    id: '/institutional-groups/organizations/',
    path: '/institutional-groups/organizations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstitutionalGroupsLaboratoriesIndexRoute =
  InstitutionalGroupsLaboratoriesIndexRouteImport.update({
    id: '/institutional-groups/laboratories/',
    path: '/institutional-groups/laboratories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstitutionalGroupsOsusCodeRoute =
  InstitutionalGroupsOsusCodeRouteImport.update({
    id: '/institutional-groups/osus/$code',
    path: '/institutional-groups/osus/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstitutionalGroupsOrganizationsRorRoute =
  InstitutionalGroupsOrganizationsRorRouteImport.update({
    id: '/institutional-groups/organizations/$ror',
    path: '/institutional-groups/organizations/$ror',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstitutionalGroupsLaboratoriesCodeRoute =
  InstitutionalGroupsLaboratoriesCodeRouteImport.update({
    id: '/institutional-groups/laboratories/$code',
    path: '/institutional-groups/laboratories/$code',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/samples/create': typeof SamplesCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/': typeof UsersIndexRoute
  '/institutional-groups/laboratories/$code': typeof InstitutionalGroupsLaboratoriesCodeRoute
  '/institutional-groups/organizations/$ror': typeof InstitutionalGroupsOrganizationsRorRoute
  '/institutional-groups/osus/$code': typeof InstitutionalGroupsOsusCodeRoute
  '/institutional-groups/laboratories/': typeof InstitutionalGroupsLaboratoriesIndexRoute
  '/institutional-groups/organizations/': typeof InstitutionalGroupsOrganizationsIndexRoute
  '/institutional-groups/osus/': typeof InstitutionalGroupsOsusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/samples/create': typeof SamplesCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users': typeof UsersIndexRoute
  '/institutional-groups/laboratories/$code': typeof InstitutionalGroupsLaboratoriesCodeRoute
  '/institutional-groups/organizations/$ror': typeof InstitutionalGroupsOrganizationsRorRoute
  '/institutional-groups/osus/$code': typeof InstitutionalGroupsOsusCodeRoute
  '/institutional-groups/laboratories': typeof InstitutionalGroupsLaboratoriesIndexRoute
  '/institutional-groups/organizations': typeof InstitutionalGroupsOrganizationsIndexRoute
  '/institutional-groups/osus': typeof InstitutionalGroupsOsusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/samples/create': typeof SamplesCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/': typeof UsersIndexRoute
  '/institutional-groups/laboratories/$code': typeof InstitutionalGroupsLaboratoriesCodeRoute
  '/institutional-groups/organizations/$ror': typeof InstitutionalGroupsOrganizationsRorRoute
  '/institutional-groups/osus/$code': typeof InstitutionalGroupsOsusCodeRoute
  '/institutional-groups/laboratories/': typeof InstitutionalGroupsLaboratoriesIndexRoute
  '/institutional-groups/organizations/': typeof InstitutionalGroupsOrganizationsIndexRoute
  '/institutional-groups/osus/': typeof InstitutionalGroupsOsusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/auth/callback'
    | '/samples/$sampleId'
    | '/samples/create'
    | '/users/$userId'
    | '/users/'
    | '/institutional-groups/laboratories/$code'
    | '/institutional-groups/organizations/$ror'
    | '/institutional-groups/osus/$code'
    | '/institutional-groups/laboratories/'
    | '/institutional-groups/organizations/'
    | '/institutional-groups/osus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/auth/callback'
    | '/samples/$sampleId'
    | '/samples/create'
    | '/users/$userId'
    | '/users'
    | '/institutional-groups/laboratories/$code'
    | '/institutional-groups/organizations/$ror'
    | '/institutional-groups/osus/$code'
    | '/institutional-groups/laboratories'
    | '/institutional-groups/organizations'
    | '/institutional-groups/osus'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/auth/callback'
    | '/samples/$sampleId'
    | '/samples/create'
    | '/users/$userId'
    | '/users/'
    | '/institutional-groups/laboratories/$code'
    | '/institutional-groups/organizations/$ror'
    | '/institutional-groups/osus/$code'
    | '/institutional-groups/laboratories/'
    | '/institutional-groups/organizations/'
    | '/institutional-groups/osus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SamplesSampleIdRoute: typeof SamplesSampleIdRoute
  SamplesCreateRoute: typeof SamplesCreateRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
  InstitutionalGroupsLaboratoriesCodeRoute: typeof InstitutionalGroupsLaboratoriesCodeRoute
  InstitutionalGroupsOrganizationsRorRoute: typeof InstitutionalGroupsOrganizationsRorRoute
  InstitutionalGroupsOsusCodeRoute: typeof InstitutionalGroupsOsusCodeRoute
  InstitutionalGroupsLaboratoriesIndexRoute: typeof InstitutionalGroupsLaboratoriesIndexRoute
  InstitutionalGroupsOrganizationsIndexRoute: typeof InstitutionalGroupsOrganizationsIndexRoute
  InstitutionalGroupsOsusIndexRoute: typeof InstitutionalGroupsOsusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/create': {
      id: '/samples/create'
      path: '/samples/create'
      fullPath: '/samples/create'
      preLoaderRoute: typeof SamplesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$sampleId': {
      id: '/samples/$sampleId'
      path: '/samples/$sampleId'
      fullPath: '/samples/$sampleId'
      preLoaderRoute: typeof SamplesSampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional-groups/osus/': {
      id: '/institutional-groups/osus/'
      path: '/institutional-groups/osus'
      fullPath: '/institutional-groups/osus/'
      preLoaderRoute: typeof InstitutionalGroupsOsusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional-groups/organizations/': {
      id: '/institutional-groups/organizations/'
      path: '/institutional-groups/organizations'
      fullPath: '/institutional-groups/organizations/'
      preLoaderRoute: typeof InstitutionalGroupsOrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional-groups/laboratories/': {
      id: '/institutional-groups/laboratories/'
      path: '/institutional-groups/laboratories'
      fullPath: '/institutional-groups/laboratories/'
      preLoaderRoute: typeof InstitutionalGroupsLaboratoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional-groups/osus/$code': {
      id: '/institutional-groups/osus/$code'
      path: '/institutional-groups/osus/$code'
      fullPath: '/institutional-groups/osus/$code'
      preLoaderRoute: typeof InstitutionalGroupsOsusCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional-groups/organizations/$ror': {
      id: '/institutional-groups/organizations/$ror'
      path: '/institutional-groups/organizations/$ror'
      fullPath: '/institutional-groups/organizations/$ror'
      preLoaderRoute: typeof InstitutionalGroupsOrganizationsRorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional-groups/laboratories/$code': {
      id: '/institutional-groups/laboratories/$code'
      path: '/institutional-groups/laboratories/$code'
      fullPath: '/institutional-groups/laboratories/$code'
      preLoaderRoute: typeof InstitutionalGroupsLaboratoriesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SamplesSampleIdRoute: SamplesSampleIdRoute,
  SamplesCreateRoute: SamplesCreateRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
  InstitutionalGroupsLaboratoriesCodeRoute:
    InstitutionalGroupsLaboratoriesCodeRoute,
  InstitutionalGroupsOrganizationsRorRoute:
    InstitutionalGroupsOrganizationsRorRoute,
  InstitutionalGroupsOsusCodeRoute: InstitutionalGroupsOsusCodeRoute,
  InstitutionalGroupsLaboratoriesIndexRoute:
    InstitutionalGroupsLaboratoriesIndexRoute,
  InstitutionalGroupsOrganizationsIndexRoute:
    InstitutionalGroupsOrganizationsIndexRoute,
  InstitutionalGroupsOsusIndexRoute: InstitutionalGroupsOsusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
