import type { GeologicalAge } from "@projet-igsn/domain/sample/age/geological-age";
import type { Location } from "@projet-igsn/domain/sample/location/model";

import { generateIgsnSuffix } from "@projet-igsn/domain/igsn/generate-igsn-suffix";

import type { SeedSample } from "./seed.ts";

type DemoRow = Omit<SeedSample, "id" | "igsn" | "published">;

type Position = NonNullable<Location["position"]>;
type Elevation = NonNullable<Position["elevation"]>;

const point = (
  longitude: number,
  latitude: number,
  elevation?: Elevation,
): Position => ({ type: "point", longitude, latitude, elevation });

const area = (
  westLongitude: number,
  eastLongitude: number,
  southLatitude: number,
  northLatitude: number,
  elevation?: Elevation,
): Position => ({
  type: "area",
  westLongitude,
  eastLongitude,
  southLatitude,
  northLatitude,
  elevation,
});

const elev = (
  min: number,
  max: number,
  unit: Elevation["unit"],
  datum: Elevation["datum"],
): Elevation => ({ min, max, unit, datum });

const on = (start: string, end: string = start) => ({
  collectionDate: { start, end },
});

const numericAge = (
  min: number,
  max: number,
  unit: "ka" | "ma" | "ga" = "ma",
) =>
  ({
    numericAgeMin: min,
    numericAgeMax: max,
    numericAgeUnit: unit,
    numericAgeYearsUnit: null,
    geologicalAgeMin: null,
    geologicalAgeMax: null,
    geologicalUnit: null,
  }) as const;

const annumAge = (
  min: number,
  max: number,
  yearsUnit: "ce" | "bce" | "bp" | "cal_bp",
) =>
  ({
    numericAgeMin: min,
    numericAgeMax: max,
    numericAgeUnit: "a",
    numericAgeYearsUnit: yearsUnit,
    geologicalAgeMin: null,
    geologicalAgeMax: null,
    geologicalUnit: null,
  }) as const;

const geologicalAge = (
  min: GeologicalAge,
  max: GeologicalAge,
  unit: string | null = null,
) =>
  ({
    numericAgeMin: null,
    numericAgeMax: null,
    numericAgeUnit: null,
    numericAgeYearsUnit: null,
    geologicalAgeMin: min,
    geologicalAgeMax: max,
    geologicalUnit: unit,
  }) as const;

const PUBLISHED: DemoRow[] = [
  {
    name: "Brittany Granite",
    owner: "marie",
    nature: "thin_section",
    type: "core.piece",
    material: "rock.igneous.plutonic.felsic.granite",
    texture: "phaneritic",
    collectionMethod: "blasting",
    specificName: "BRT-GRN-2025-07",
    location: {
      position: point(-3.5, 48.2),
      region: { kind: "continent", country: "FR" },
      localityName: "Ploumanac'h quarry",
    },
    description: on("2025-05-12"),
    age: numericAge(295, 305),
    availability: "exists",
  },
  {
    name: "Corsica Granodiorite",
    owner: "jean",
    nature: "rock_chips",
    type: "core.slab",
    material: "rock.igneous.plutonic.felsic.granodiorite",
    texture: "porphyritic",
    collectionMethod: "manual",
    specificName: "COR-GD-2025-03",
    location: {
      position: point(9.1, 42.15, elev(800, 800, "m", "msl")),
      region: { kind: "continent", country: "FR" },
    },
    description: on("2025-06-20"),
    availability: "exists",
  },
  {
    name: "Aar Massif Tonalite",
    owner: "sophie",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.plutonic.felsic.tonalite",
    texture: "phaneritic",
    collectionMethod: "manual",
    location: {
      position: point(8.3, 46.7, elev(2200, 2200, "m", "msl")),
      region: { kind: "continent", country: "CH" },
    },
    description: on("2024-08-01"),
    availability: "exists",
  },
  {
    name: "Bushveld Gabbro",
    owner: "pierre",
    nature: "polished_section",
    type: "core.piece",
    material: "rock.igneous.plutonic.mafic.gabbro",
    texture: "cumulate",
    collectionMethod: "blasting",
    specificName: "BV-MAG-88",
    location: {
      position: point(29.5, -25.0),
      region: { kind: "continent", country: "ZA" },
    },
    description: on("2025-02-14"),
    availability: "exists",
  },
  {
    name: "Harz Norite",
    owner: "camille",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.plutonic.mafic.norite",
    texture: "poikilitic",
    collectionMethod: "manual",
    location: {
      position: point(10.7, 51.9),
      region: { kind: "continent", country: "DE" },
    },
    description: on("2024-09-03"),
    availability: "exists",
  },
  {
    name: "Oman Ophiolite Peridotite",
    owner: "marie",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.plutonic.ultramafic.peridotite",
    texture: "phaneritic",
    collectionMethod: "manual",
    specificName: "OM-OPH-2025-11",
    location: {
      position: point(58.1, 23.1, elev(450, 450, "m", "msl")),
      region: { kind: "continent", country: "OM" },
    },
    description: on("2025-03-30"),
    availability: "exists",
  },
  {
    name: "Oslo Rift Syenite",
    owner: "jean",
    nature: "thin_section",
    type: "core.section",
    material: "rock.igneous.plutonic.intermediate.syenite",
    texture: "porphyritic",
    collectionMethod: "blasting",
    location: {
      position: point(10.7, 59.9),
      region: { kind: "continent", country: "NO" },
    },
    description: on("2024-07-19"),
    availability: "exists",
  },
  {
    name: "Massif Central Basalt",
    owner: "sophie",
    nature: "hand_sample",
    type: "core.half_round",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "vesicular",
    collectionMethod: "manual",
    specificName: "MC-BAS-2025-19",
    location: {
      position: point(2.96, 45.77, elev(1050, 1050, "m", "msl")),
      region: { kind: "continent", country: "FR" },
    },
    description: on("2025-06-15"),
    availability: "exists",
  },
  {
    name: "Reykjanes Ridge Basalt",
    owner: "pierre",
    nature: "rock_chips",
    type: "dredge",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "aphanitic",
    collectionMethod: "dredging.chain_bag",
    specificName: "AT-2025-RR03",
    collectionMethodDescription: "Chain-bag dredge on the axial ridge flank",
    location: {
      position: area(-30.5, -29.8, 56.8, 57.2, elev(-1520, -1520, "m", "msl")),
      region: { kind: "ocean", oceanSea: "atlantic_ocean" },
      navigationType: "GPS",
    },
    description: on("2025-04-08"),
    availability: "exists",
  },
  {
    name: "Etna Trachyte",
    owner: "camille",
    nature: "thin_section",
    type: "individual_sample",
    material: "rock.igneous.volcanic.intermediate.trachyte",
    texture: "porphyritic",
    collectionMethod: "manual",
    location: {
      position: point(15.0, 37.75, elev(2900, 2900, "m", "msl")),
      region: { kind: "continent", country: "IT" },
    },
    description: on("2025-05-01"),
    availability: "exists",
  },
  {
    name: "Yellowstone Rhyolite",
    owner: "marie",
    nature: "rock_chips",
    type: "individual_sample",
    material: "rock.igneous.volcanic.felsic.rhyolite",
    texture: "glassy",
    collectionMethod: "manual",
    location: {
      position: point(-110.6, 44.6, elev(2400, 2400, "m", "wgs84")),
      region: { kind: "continent", country: "US" },
    },
    description: on("2024-06-11"),
    availability: "exists",
  },
  {
    name: "Andean Andesite",
    owner: "jean",
    nature: "thin_section",
    type: "individual_sample",
    material: "rock.igneous.volcanic.intermediate.andesite",
    texture: "microlitic",
    collectionMethod: "manual",
    location: {
      position: point(-70.0, -23.0, elev(3800, 3800, "m", "msl")),
      region: { kind: "continent", country: "CL" },
    },
    description: on("2025-01-22"),
    availability: "exists",
  },
  {
    name: "Barberton Komatiite",
    owner: "sophie",
    nature: "polished_section",
    type: "individual_sample",
    material: "rock.igneous.volcanic.ultramafic.komatiite",
    texture: "aphanitic",
    collectionMethod: "manual",
    location: {
      position: point(31.0, -25.8),
      region: { kind: "continent", country: "ZA" },
    },
    description: on("2024-10-05"),
    availability: "exists",
  },
  {
    name: "Canary Phonolite",
    owner: "pierre",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.volcanic.intermediate.phonolite",
    texture: "porphyritic",
    collectionMethod: "manual",
    location: {
      position: point(-16.6, 28.3, elev(1900, 1900, "m", "msl")),
      region: { kind: "continent", country: "ES" },
    },
    description: on("2025-02-02"),
    availability: "exists",
  },
  {
    name: "Deccan Picrite",
    owner: "camille",
    nature: "rock_chips",
    type: "individual_sample",
    material: "rock.igneous.volcanic.ultramafic.picrite",
    texture: "aphanitic",
    collectionMethod: "manual",
    location: {
      position: point(73.8, 18.5),
      region: { kind: "continent", country: "IN" },
    },
    description: on("2024-11-20"),
    availability: "exists",
  },
  {
    name: "Kimberley Kimberlite",
    owner: "marie",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.volcanic.exotic.kimberlite",
    texture: "porphyritic",
    collectionMethod: "manual",
    location: {
      position: point(24.77, -28.74),
      region: { kind: "continent", country: "ZA" },
    },
    description: on("2025-03-11"),
    availability: "exists",
  },
  {
    name: "Carrara Marble",
    owner: "jean",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.metamorphic.strongly_metamorphosed.marble",
    metamorphicFacies: "greenschist",
    collectionMethod: "blasting",
    location: {
      position: point(10.1, 44.08),
      region: { kind: "continent", country: "IT" },
      localityName: "Carrara quarry",
    },
    description: on("2024-05-30"),
    availability: "exists",
  },
  {
    name: "Alpine Mica Schist",
    owner: "sophie",
    nature: "thin_section",
    type: "core.piece",
    material: "rock.metamorphic.strongly_metamorphosed.mica_schist",
    metamorphicFacies: "greenschist",
    collectionMethod: "manual",
    location: {
      position: point(7.0, 45.9),
      region: { kind: "continent", country: "IT" },
    },
    description: on("2025-01-15"),
    availability: "exists",
  },
  {
    name: "Lofoten Gneiss",
    owner: "pierre",
    nature: "polished_section",
    type: "individual_sample",
    material: "rock.metamorphic.strongly_metamorphosed.gneiss",
    metamorphicFacies: "amphibolite",
    collectionMethod: "manual",
    location: {
      position: point(13.6, 68.2),
      region: { kind: "continent", country: "NO" },
    },
    description: on("2024-08-22"),
    availability: "exists",
  },
  {
    name: "Western Gneiss Eclogite",
    owner: "camille",
    nature: "thin_section",
    type: "core.piece",
    material: "rock.metamorphic.strongly_metamorphosed.eclogite",
    metamorphicFacies: "eclogite",
    collectionMethod: "manual",
    location: {
      position: point(6.5, 61.9),
      region: { kind: "continent", country: "NO" },
    },
    description: on("2025-02-27"),
    availability: "exists",
  },
  {
    name: "Franciscan Blueschist",
    owner: "marie",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.metamorphic.strongly_metamorphosed.glaucophanite",
    metamorphicFacies: "blueschist",
    collectionMethod: "manual",
    location: {
      position: point(-122.5, 37.8),
      region: { kind: "continent", country: "US" },
    },
    description: on("2024-09-14"),
    availability: "exists",
  },
  {
    name: "Highland Quartzite",
    owner: "jean",
    nature: "rock_chips",
    type: "individual_sample",
    material: "rock.metamorphic.strongly_metamorphosed.quartzite",
    metamorphicFacies: "amphibolite",
    collectionMethod: "manual",
    location: {
      position: point(-5.0, 58.2),
      region: { kind: "continent", country: "GB" },
    },
    description: on("2025-04-19"),
    availability: "exists",
  },
  {
    name: "Welsh Slate Series",
    owner: "sophie",
    nature: "thick_section",
    type: "serie_of_sample",
    material: "rock.metamorphic.strongly_metamorphosed.slate",
    metamorphicFacies: "greenschist",
    collectionMethod: "blasting",
    location: {
      position: point(-4.0, 53.0),
      region: { kind: "continent", country: "GB" },
    },
    description: on("2024-07-07"),
    availability: "exists",
  },
  {
    name: "Lapland Granulite",
    owner: "pierre",
    nature: "thin_section",
    type: "individual_sample",
    material: "rock.metamorphic.strongly_metamorphosed.granulite",
    metamorphicFacies: "granulite",
    collectionMethod: "manual",
    location: {
      position: point(26.0, 68.5),
      region: { kind: "continent", country: "FI" },
    },
    description: on("2025-03-05"),
    availability: "exists",
  },
  {
    name: "Ivrea Amphibolite",
    owner: "camille",
    nature: "polished_section",
    type: "core.section",
    material: "rock.metamorphic.strongly_metamorphosed.amphibolite",
    metamorphicFacies: "amphibolite",
    collectionMethod: "manual",
    location: {
      position: point(8.0, 45.7),
      region: { kind: "continent", country: "IT" },
    },
    description: on("2024-10-30"),
    availability: "exists",
  },
  {
    name: "Zermatt Metabasalt",
    owner: "marie",
    nature: "thin_section",
    type: "individual_sample",
    material:
      "rock.metamorphic.weakly_metamorphosed.meta_igneous_rock.volcanic.mafic.basalt",
    texture: "aphanitic",
    metamorphicFacies: "greenschist",
    collectionMethod: "manual",
    location: {
      position: point(7.1, 45.5, elev(2500, 2500, "m", "msl")),
      region: { kind: "continent", country: "IT" },
    },
    description: on("2025-01-08"),
    availability: "exists",
  },
  {
    name: "Aosta Metagranite",
    owner: "jean",
    nature: "thin_section",
    type: "individual_sample",
    material:
      "rock.metamorphic.weakly_metamorphosed.meta_igneous_rock.plutonic.felsic.granite",
    texture: "phaneritic",
    metamorphicFacies: "greenschist",
    collectionMethod: "manual",
    location: {
      position: point(6.9, 45.2),
      region: { kind: "continent", country: "IT" },
    },
    description: on("2025-02-18"),
    availability: "exists",
  },
  {
    name: "Fontainebleau Sandstone",
    owner: "sophie",
    nature: "rock_powder",
    type: "individual_sample",
    material: "rock.sedimentary.clastic_sedimentary_rock.sandstone",
    collectionMethod: "manual",
    location: {
      position: point(2.7, 48.4),
      region: { kind: "continent", country: "FR" },
    },
    description: on("2024-06-01"),
    availability: "exists",
  },
  {
    name: "Jura Limestone",
    owner: "pierre",
    nature: "rock_chips",
    type: "individual_sample",
    material:
      "rock.sedimentary.biochemical_and_chemical_sedimentary_rock.carbonate_rock.limestone",
    collectionMethod: "manual",
    location: {
      position: point(5.9, 46.7),
      region: { kind: "continent", country: "FR" },
    },
    description: on("2025-05-25"),
    availability: "exists",
  },
  {
    name: "Dolomites Dolostone",
    owner: "camille",
    nature: "hand_sample",
    type: "individual_sample",
    material:
      "rock.sedimentary.biochemical_and_chemical_sedimentary_rock.carbonate_rock.dolostone",
    collectionMethod: "manual",
    location: {
      position: point(11.9, 46.4, elev(2100, 2100, "m", "msl")),
      region: { kind: "continent", country: "IT" },
    },
    description: on("2024-08-18"),
    availability: "exists",
  },
  {
    name: "Franconian Chert",
    owner: "marie",
    nature: "rock_chips",
    type: "individual_sample",
    material:
      "rock.sedimentary.biochemical_and_chemical_sedimentary_rock.siliceous_rock.chert",
    collectionMethod: "manual",
    location: {
      position: point(11.0, 49.8),
      region: { kind: "continent", country: "DE" },
    },
    description: on("2025-01-30"),
    availability: "exists",
  },
  {
    name: "Paris Basin Gypsum",
    owner: "jean",
    nature: "hand_sample",
    type: "individual_sample",
    material:
      "rock.sedimentary.biochemical_and_chemical_sedimentary_rock.evaporite.gypsum_stone",
    collectionMethod: "manual",
    location: {
      position: point(2.35, 48.9),
      region: { kind: "continent", country: "FR" },
    },
    description: on("2024-09-27"),
    availability: "exists",
  },
  {
    name: "Ruhr Coal Core",
    owner: "sophie",
    nature: "sample_fragment",
    type: "core.whole_round",
    material:
      "rock.sedimentary.biochemical_and_chemical_sedimentary_rock.organic_rich_rock.coal",
    collectionMethod: "coring.drill_corer",
    specificName: "RUHR-BH-14",
    location: {
      position: point(7.2, 51.5, elev(-800, -800, "m", "msl")),
      region: { kind: "continent", country: "DE" },
    },
    description: on("2024-11-11"),
    availability: "exists",
  },
  {
    name: "North Sea Mudstone Core",
    owner: "pierre",
    nature: "sample_fragment",
    type: "core.section",
    material: "rock.sedimentary.clastic_sedimentary_rock.mudstone",
    collectionMethod: "coring.drill_corer",
    specificName: "NS-42/10-A",
    location: {
      position: point(2.0, 57.0, elev(-2500, -2500, "m", "msl")),
      region: { kind: "ocean", oceanSea: "north_sea" },
      navigationType: "GPS",
    },
    description: on("2025-02-09"),
    availability: "exists",
  },
  {
    name: "TAG Sulfide Chimney",
    owner: "camille",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.hydrothermal.sulfide",
    collectionMethod: "grab.rov",
    collectionMethodDescription: "ROV manipulator grab of an active chimney",
    location: {
      position: point(-44.83, 26.14, elev(-3620, -3620, "m", "msl")),
      region: { kind: "ocean", oceanSea: "atlantic_ocean" },
      navigationType: "USBL",
    },
    description: on("2025-03-22"),
    availability: "exists",
  },
  {
    name: "Rainbow Hydrothermal Breccia",
    owner: "marie",
    nature: "rock_chips",
    type: "individual_sample",
    material: "rock.hydrothermal.breccia",
    collectionMethod: "grab.hov",
    location: {
      position: point(-33.9, 36.23, elev(-2300, -2300, "m", "msl")),
      region: { kind: "ocean", oceanSea: "atlantic_ocean" },
      navigationType: "DVL/LBL",
    },
    description: on("2024-10-16"),
    availability: "exists",
  },
  {
    name: "Lost City Carbonate",
    owner: "jean",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.hydrothermal.carbonate",
    collectionMethod: "grab.rov",
    location: {
      position: point(-30.13, 30.13, elev(-750, -750, "m", "msl")),
      region: { kind: "ocean", oceanSea: "atlantic_ocean" },
      navigationType: "USBL",
    },
    description: on("2025-04-27"),
    availability: "exists",
  },
  {
    name: "Pacific Abyssal Clay",
    owner: "sophie",
    nature: "separated_materials",
    type: "core.section",
    material: "sediment.exogenous_detritic.clay",
    collectionMethod: "coring.gravity_corer.giant",
    specificName: "PAC-GC-07",
    collectionMethodDescription: "Giant gravity corer, 8 m recovery",
    location: {
      position: point(-140.0, 30.0, elev(-5000, -5000, "m", "msl")),
      region: { kind: "ocean", oceanSea: "pacific_ocean" },
      navigationType: "GPS",
    },
    description: on("2024-07-30"),
    availability: "exists",
  },
  {
    name: "Loire Sand",
    owner: "pierre",
    nature: "rock_powder",
    type: "individual_sample",
    material: "sediment.exogenous_detritic.sand.medium_sand",
    collectionMethod: "manual",
    location: {
      position: point(-1.5, 47.2),
      region: { kind: "continent", country: "FR" },
    },
    description: on("2025-05-06"),
    availability: "exists",
  },
  {
    name: "Rhine Gravel",
    owner: "camille",
    nature: "multiple_sample",
    type: "individual_sample",
    material: "sediment.exogenous_detritic.gravel.pebble",
    collectionMethod: "manual",
    location: {
      position: point(7.6, 47.6),
      region: { kind: "continent", country: "DE" },
    },
    description: on("2024-06-25"),
    availability: "exists",
  },
  {
    name: "Champagne Loess Silt",
    owner: "marie",
    nature: "rock_powder",
    type: "individual_sample",
    material: "sediment.exogenous_detritic.silt.medium_silt",
    collectionMethod: "manual",
    location: {
      position: point(4.9, 48.3),
      region: { kind: "continent", country: "FR" },
    },
    description: on("2025-01-19"),
    age: annumAge(12000, 25000, "bp"),
    availability: "exists",
  },
  {
    name: "Vesuvius Volcanic Ash",
    owner: "jean",
    nature: "rock_powder",
    type: "individual_sample",
    material: "sediment.volcano_detritic.ash.glass",
    collectionMethod: "manual",
    location: {
      position: point(14.43, 40.82),
      region: { kind: "continent", country: "IT" },
    },
    description: on("2024-09-09"),
    age: annumAge(79, 79, "ce"),
    availability: "exists",
  },
  {
    name: "Bahamas Carbonate Ooze",
    owner: "sophie",
    nature: "sample_fragment",
    type: "core.section",
    material: "sediment.biogenic.carbonate.mud_supported.mudstone",
    collectionMethod: "coring.piston_corer.giant",
    location: {
      position: point(-76.0, 24.0, elev(-600, -600, "m", "msl")),
      region: { kind: "ocean", oceanSea: "atlantic_ocean" },
      navigationType: "GPS",
    },
    description: on("2025-02-21"),
    availability: "exists",
  },
  {
    name: "Southern Ocean Diatom Ooze",
    owner: "pierre",
    nature: "separated_materials",
    type: "core.section",
    material: "sediment.biogenic.siliceous.diatoms",
    collectionMethod: "coring.gravity_corer.giant",
    location: {
      position: point(170.0, -60.0, elev(-3500, -3500, "m", "msl")),
      region: { kind: "ocean", oceanSea: "pacific_ocean" },
      navigationType: "GPS",
    },
    description: on("2024-12-03"),
    availability: "exists",
  },
  {
    name: "Irish Bog Peat",
    owner: "camille",
    nature: "sample_fragment",
    type: "individual_sample",
    material: "sediment.biogenic.organic_rich.peat",
    collectionMethod: "probe",
    location: {
      position: point(-8.0, 53.4),
      region: { kind: "continent", country: "IE" },
    },
    description: on("2025-03-17"),
    age: annumAge(2000, 8000, "cal_bp"),
    availability: "exists",
  },
  {
    name: "Red Sea Evaporitic Precipitate",
    owner: "marie",
    nature: "rock_powder",
    type: "individual_sample",
    material: "sediment.physico_chemical.precipitates.evaporitic",
    collectionMethod: "grab.grab",
    location: {
      position: point(38.5, 21.0, elev(-1800, -1800, "m", "msl")),
      region: { kind: "ocean", oceanSea: "red_sea" },
      navigationType: "GPS",
    },
    description: on("2024-08-12"),
    age: annumAge(1000, 3000, "bce"),
    availability: "exists",
  },
  {
    name: "Alpine Quartz Crystal",
    owner: "jean",
    nature: "hand_sample",
    type: "individual_sample",
    material: "mineral",
    collectionMethod: "manual",
    location: {
      position: point(8.5, 46.5, elev(2600, 2600, "m", "msl")),
      region: { kind: "continent", country: "CH" },
    },
    description: on("2024-07-01"),
    availability: "exists",
  },
  {
    name: "Rio Tinto Pyrite",
    owner: "sophie",
    nature: "polished_section",
    type: "individual_sample",
    material: "mineral",
    collectionMethod: "manual",
    location: {
      position: point(-6.6, 37.7),
      region: { kind: "continent", country: "ES" },
    },
    description: on("2025-04-14"),
    availability: "exists",
  },
  {
    name: "Minas Gerais Beryl",
    owner: "pierre",
    nature: "hand_sample",
    type: "individual_sample",
    material: "mineral",
    collectionMethod: "manual",
    location: {
      position: point(-43.0, -18.0),
      region: { kind: "continent", country: "BR" },
    },
    description: on("2024-10-22"),
    availability: "exists",
  },
  {
    name: "Normandy Ammonite",
    owner: "camille",
    nature: "hand_sample",
    type: "individual_sample",
    material: "fossil",
    collectionMethod: "manual",
    location: {
      position: point(0.2, 49.3),
      region: { kind: "continent", country: "FR" },
    },
    description: on("2025-05-18"),
    age: geologicalAge(10, 12, "Terres Noires Formation"),
    availability: "exists",
  },
  {
    name: "Bohemian Trilobite",
    owner: "marie",
    nature: "hand_sample",
    type: "individual_sample",
    material: "fossil",
    collectionMethod: "manual",
    location: {
      position: point(14.0, 50.0),
      region: { kind: "continent", country: "CZ" },
    },
    description: on("2024-09-19"),
    age: geologicalAge(31, 34),
    availability: "exists",
  },
  {
    name: "Dorset Belemnite",
    owner: "jean",
    nature: "hand_sample",
    type: "individual_sample",
    material: "fossil",
    collectionMethod: "manual",
    location: {
      position: point(-2.5, 50.7),
      region: { kind: "continent", country: "GB" },
    },
    description: on("2025-01-27"),
    age: geologicalAge(8, 10),
    availability: "exists",
  },
  {
    name: "Synthetic Corundum",
    owner: "sophie",
    nature: "inapplicable",
    type: "inapplicable",
    material: "synthetic_rock_mineral",
    collectionMethod: "experimental_apparatus",
    description: on("2025-06-01"),
    availability: "exists",
  },
  {
    name: "Synthetic Forsterite",
    owner: "pierre",
    nature: "thin_section",
    type: "inapplicable",
    material: "synthetic_rock_mineral",
    collectionMethod: "experimental_apparatus",
    description: on("2024-11-30"),
    availability: "exists",
  },
  {
    name: "Sahara Ordinary Chondrite",
    owner: "camille",
    nature: "hand_sample",
    type: "individual_sample",
    material:
      "extraterrestrial_rock.meteorites.chondrites.ordinary_chondrites.h",
    collectionMethod: "manual",
    location: {
      position: point(1.0, 27.5),
      region: { kind: "continent", country: "DZ" },
    },
    description: on("2024-06-05"),
    availability: "exists",
  },
  {
    name: "Victoria CM Chondrite",
    owner: "marie",
    nature: "thin_section",
    type: "individual_sample",
    material:
      "extraterrestrial_rock.meteorites.chondrites.carbonaceous_chondrites.cm",
    collectionMethod: "manual",
    location: {
      position: point(145.2, -36.6),
      region: { kind: "continent", country: "AU" },
    },
    description: on("2025-02-11"),
    availability: "exists",
  },
  {
    name: "Canyon Diablo Iron Meteorite",
    owner: "jean",
    nature: "polished_section",
    type: "individual_sample",
    material:
      "extraterrestrial_rock.meteorites.achondrites.iron_meteorite.iiab",
    collectionMethod: "manual",
    location: {
      position: point(-111.02, 35.03),
      region: { kind: "continent", country: "US" },
    },
    description: on("2024-08-08"),
    availability: "exists",
  },
  {
    name: "NWA Shergottite",
    owner: "sophie",
    nature: "thin_section",
    type: "individual_sample",
    material:
      "extraterrestrial_rock.meteorites.achondrites.stony_achondrite.martian_meteorite.shergottite",
    collectionMethod: "manual",
    specificName: "NWA-8686",
    location: {
      position: point(-5.0, 28.0),
      region: { kind: "continent", country: "MA" },
    },
    description: on("2025-03-01"),
    availability: "exists",
  },
  {
    name: "Antarctic Lunar Meteorite",
    owner: "pierre",
    nature: "thin_section",
    type: "individual_sample",
    material:
      "extraterrestrial_rock.meteorites.achondrites.stony_achondrite.lunar_meteorite.basalt",
    collectionMethod: "manual",
    specificName: "MIL-2024-01",
    location: {
      position: point(160.0, -76.7),
      region: { kind: "continent", country: "AQ" },
    },
    description: on("2024-12-20"),
    availability: "exists",
  },
  {
    name: "Apollo 15 Mare Basalt",
    owner: "camille",
    nature: "hand_sample",
    type: "individual_sample",
    material: "extraterrestrial_rock.returned_samples.lunar_sample.rock",
    collectionMethod: "spatial_mission",
    specificName: "Apollo 15 / 15555",
    description: on("2024-05-01"),
    age: numericAge(3, 4, "ga"),
    availability: "exists",
  },
  {
    name: "Apollo 17 Lunar Soil",
    owner: "marie",
    nature: "separated_materials",
    type: "individual_sample",
    material: "extraterrestrial_rock.returned_samples.lunar_sample.soil",
    collectionMethod: "spatial_mission",
    specificName: "Apollo 17 / 70017",
    description: on("2024-05-02"),
    availability: "exists",
  },
  {
    name: "Hayabusa2 Ryugu Grain",
    owner: "jean",
    nature: "sample_fragment",
    type: "individual_sample",
    material: "extraterrestrial_rock.returned_samples.asteroid.ryugu",
    collectionMethod: "spatial_mission",
    specificName: "Hayabusa2 / C0002",
    description: on("2025-01-05"),
    age: numericAge(4, 5, "ga"),
    availability: "exists",
  },
  {
    name: "OSIRIS-REx Bennu Grain",
    owner: "sophie",
    nature: "sample_fragment",
    type: "individual_sample",
    material: "extraterrestrial_rock.returned_samples.asteroid.bennu",
    collectionMethod: "spatial_mission",
    specificName: "OSIRIS-REx",
    description: on("2025-01-06"),
    availability: "exists",
  },
  {
    name: "Hayabusa Itokawa Grain",
    owner: "pierre",
    nature: "sample_fragment",
    type: "individual_sample",
    material: "extraterrestrial_rock.returned_samples.asteroid.itokawa",
    collectionMethod: "spatial_mission",
    specificName: "Hayabusa / RA-QD02",
    description: on("2024-04-15"),
    availability: "exists",
  },
  {
    name: "Legacy Archive Basalt",
    owner: "camille",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "aphanitic",
    collectionMethod: "unknown",
    location: {
      position: point(2.5, 45.0),
      region: { kind: "continent", country: "FR" },
    },
    description: on("2024-01-10"),
    availability: "no_longer_exists",
  },
  {
    name: "Camera-Tow Ridge Basalt",
    owner: "marie",
    nature: "rock_chips",
    type: "dredge",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "vesicular",
    collectionMethod: "camera_sled_camera_tow",
    location: {
      position: area(-45.2, -44.6, 25.8, 26.4, elev(-3600, -3400, "m", "msl")),
      region: { kind: "ocean", oceanSea: "atlantic_ocean" },
      navigationType: "GPS",
    },
    description: on("2025-03-28"),
    age: numericAge(500, 1500, "ka"),
    availability: "exists",
  },
  {
    name: "Sediment Trap Particulate",
    owner: "jean",
    nature: "separated_materials",
    type: "individual_sample",
    material: "sediment.biogenic.siliceous.diatoms",
    collectionMethod: "sediment_trap",
    location: {
      position: point(-25.0, 49.0, elev(-1000, -1000, "m", "msl")),
      region: { kind: "ocean", oceanSea: "atlantic_ocean" },
      navigationType: "GPS",
    },
    description: on("2024-10-01"),
    availability: "exists",
  },
  {
    name: "Rhone Suspended Sediment",
    owner: "sophie",
    nature: "residue",
    type: "individual_sample",
    material: "sediment.exogenous_detritic.silt.fine_silt",
    collectionMethod: "suspended_sediment",
    location: {
      position: point(4.85, 45.75),
      region: { kind: "continent", country: "FR" },
    },
    description: on("2025-04-02"),
    availability: "exists",
  },
  {
    name: "IODP Basement Gabbro",
    owner: "pierre",
    nature: "thin_section",
    type: "core.whole_round",
    material: "rock.igneous.plutonic.mafic.gabbro",
    texture: "phaneritic",
    collectionMethod: "coring.drill_corer",
    specificName: "IODP-U1309D",
    collectionMethodDescription: "Rotary drill core, 3.2 m recovery",
    location: {
      position: point(-46.0, 23.0, elev(-4200, -4200, "m", "msl")),
      region: { kind: "ocean", oceanSea: "atlantic_ocean" },
      navigationType: "GPS",
    },
    description: on("2024-11-05"),
    availability: "exists",
  },
  {
    name: "Biscay Shelf Sand Boxcore",
    owner: "camille",
    nature: "sem_mount",
    type: "core.piece",
    material: "sediment.exogenous_detritic.sand.fine_sand",
    collectionMethod: "coring.box_corer",
    location: {
      position: point(-4.0, 48.5, elev(-120, -120, "m", "msl")),
      region: { kind: "ocean", oceanSea: "bay_of_biscay" },
      navigationType: "GPS",
    },
    description: on("2025-02-15"),
    availability: "exists",
  },
  {
    name: "Sanbagawa Blueschist",
    owner: "marie",
    nature: "thin_section",
    type: "individual_sample",
    material: "rock.metamorphic.strongly_metamorphosed.glaucophanite",
    metamorphicFacies: "blueschist",
    collectionMethod: "manual",
    location: {
      position: point(133.5, 33.8),
      region: { kind: "continent", country: "JP" },
    },
    description: on("2025-04-25"),
    availability: "exists",
  },
  {
    name: "Otago Schist",
    owner: "jean",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.metamorphic.strongly_metamorphosed.mica_schist",
    metamorphicFacies: "greenschist",
    collectionMethod: "manual",
    location: {
      position: point(169.7, -45.3),
      region: { kind: "continent", country: "NZ" },
    },
    description: on("2024-11-08"),
    availability: "exists",
  },
  {
    name: "Kilauea Basalt",
    owner: "sophie",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "vesicular",
    collectionMethod: "manual",
    location: {
      position: point(-155.29, 19.42, elev(1200, 1200, "m", "msl")),
      region: { kind: "continent", country: "US" },
    },
    description: on("2025-05-30"),
    availability: "exists",
  },
  {
    name: "Acasta Gneiss",
    owner: "pierre",
    nature: "thin_section",
    type: "core.piece",
    material: "rock.metamorphic.strongly_metamorphosed.gneiss",
    metamorphicFacies: "amphibolite",
    collectionMethod: "manual",
    location: {
      position: point(-115.5, 65.2),
      region: { kind: "continent", country: "CA" },
    },
    description: on("2024-07-22"),
    availability: "exists",
  },
  {
    name: "Dabie Shan Eclogite",
    owner: "camille",
    nature: "thin_section",
    type: "core.piece",
    material: "rock.metamorphic.strongly_metamorphosed.eclogite",
    metamorphicFacies: "eclogite",
    collectionMethod: "manual",
    location: {
      position: point(114.0, 30.8),
      region: { kind: "continent", country: "CN" },
    },
    description: on("2025-03-14"),
    availability: "exists",
  },
  {
    name: "Toba Rhyolitic Tuff",
    owner: "marie",
    nature: "rock_chips",
    type: "individual_sample",
    material: "rock.igneous.volcanic.felsic.rhyolite",
    texture: "glassy",
    collectionMethod: "manual",
    location: {
      position: point(98.9, 2.6),
      region: { kind: "continent", country: "ID" },
    },
    description: on("2024-10-09"),
    availability: "exists",
  },
  {
    name: "Krafla Basalt",
    owner: "jean",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "aphanitic",
    collectionMethod: "manual",
    location: {
      position: point(-16.78, 65.72),
      region: { kind: "continent", country: "IS" },
    },
    description: on("2025-06-28"),
    availability: "exists",
  },
  {
    name: "Siberian Traps Basalt",
    owner: "sophie",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "vesicular",
    collectionMethod: "manual",
    location: {
      position: point(88.2, 69.3),
      region: { kind: "continent", country: "RU" },
    },
    description: on("2024-08-30"),
    availability: "exists",
  },
  {
    name: "Puy de Dôme Trachyte",
    owner: "pierre",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.volcanic.intermediate.trachyte",
    texture: "porphyritic",
    collectionMethod: "manual",
    location: {
      position: point(2.964, 45.772, elev(1465, 1465, "m", "msl")),
      region: { kind: "continent", country: "FR" },
      localityName: "Puy de Dôme",
    },
    description: on("2025-06-18"),
    availability: "exists",
  },
  {
    name: "Puy de Côme Basalt",
    owner: "camille",
    nature: "rock_chips",
    type: "individual_sample",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "vesicular",
    collectionMethod: "manual",
    location: {
      position: point(2.94, 45.81, elev(1250, 1250, "m", "msl")),
      region: { kind: "continent", country: "FR" },
      localityName: "Puy de Côme",
    },
    description: on("2025-06-19"),
    availability: "exists",
  },
  {
    name: "Puy Pariou Basalt",
    owner: "marie",
    nature: "thin_section",
    type: "individual_sample",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "aphanitic",
    collectionMethod: "manual",
    location: {
      position: point(2.966, 45.798, elev(1210, 1210, "m", "msl")),
      region: { kind: "continent", country: "FR" },
      localityName: "Puy Pariou",
    },
    description: on("2025-06-20"),
    availability: "exists",
  },
  {
    name: "Puy de la Vache Scoria",
    owner: "jean",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "vesicular",
    collectionMethod: "manual",
    location: {
      position: point(2.98, 45.7, elev(1160, 1160, "m", "msl")),
      region: { kind: "continent", country: "FR" },
      localityName: "Puy de la Vache",
    },
    description: on("2025-06-21"),
    availability: "exists",
  },
  {
    name: "Puy Chopine Domite",
    owner: "sophie",
    nature: "thin_section",
    type: "individual_sample",
    material: "rock.igneous.volcanic.intermediate.trachyte",
    texture: "porphyritic",
    collectionMethod: "manual",
    location: {
      position: point(2.97, 45.83, elev(1180, 1180, "m", "msl")),
      region: { kind: "continent", country: "FR" },
      localityName: "Puy Chopine",
    },
    description: on("2025-06-22"),
    availability: "exists",
  },
  {
    name: "Afar Rift Basalt",
    owner: "pierre",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "vesicular",
    collectionMethod: "manual",
    location: {
      position: point(40.6, 11.8),
      region: { kind: "continent", country: "ET" },
    },
    description: on("2025-02-04"),
    availability: "exists",
  },
  {
    name: "Isua Amphibolite",
    owner: "camille",
    nature: "thin_section",
    type: "core.piece",
    material: "rock.metamorphic.strongly_metamorphosed.amphibolite",
    metamorphicFacies: "amphibolite",
    collectionMethod: "manual",
    location: {
      position: point(-50.0, 65.1),
      region: { kind: "continent", country: "GL" },
    },
    description: on("2024-07-14"),
    availability: "exists",
  },
  {
    name: "Himalayan Gneiss",
    owner: "marie",
    nature: "thin_section",
    type: "individual_sample",
    material: "rock.metamorphic.strongly_metamorphosed.gneiss",
    metamorphicFacies: "amphibolite",
    collectionMethod: "manual",
    location: {
      position: point(86.9, 28.0, elev(5200, 5200, "m", "msl")),
      region: { kind: "continent", country: "NP" },
    },
    description: on("2024-09-25"),
    availability: "exists",
  },
  {
    name: "Patagonian Plateau Basalt",
    owner: "jean",
    nature: "rock_chips",
    type: "individual_sample",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "aphanitic",
    collectionMethod: "manual",
    location: {
      position: point(-70.0, -46.5),
      region: { kind: "continent", country: "AR" },
    },
    description: on("2025-01-12"),
    availability: "exists",
  },
  {
    name: "Popocatépetl Andesite",
    owner: "sophie",
    nature: "thin_section",
    type: "individual_sample",
    material: "rock.igneous.volcanic.intermediate.andesite",
    texture: "microlitic",
    collectionMethod: "manual",
    location: {
      position: point(-98.62, 19.02, elev(4000, 4000, "m", "msl")),
      region: { kind: "continent", country: "MX" },
    },
    description: on("2025-05-08"),
    availability: "exists",
  },
  {
    name: "Jeju Island Basalt",
    owner: "pierre",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.volcanic.mafic.basalt",
    texture: "vesicular",
    collectionMethod: "manual",
    location: {
      position: point(126.5, 33.4),
      region: { kind: "continent", country: "KR" },
    },
    description: on("2024-10-27"),
    availability: "exists",
  },
  {
    name: "Papuan Ophiolite Peridotite",
    owner: "camille",
    nature: "hand_sample",
    type: "individual_sample",
    material: "rock.igneous.plutonic.ultramafic.peridotite",
    texture: "phaneritic",
    collectionMethod: "manual",
    location: {
      position: point(147.7, -9.4),
      region: { kind: "continent", country: "PG" },
    },
    description: on("2025-03-19"),
    availability: "exists",
  },
];

const DRAFTS: DemoRow[] = [
  {
    name: "Unclassified field sample 001",
    owner: "marie",
    nature: "hand_sample",
  },
  {
    name: "Volcano flank sample (classification pending)",
    owner: "jean",
    nature: "rock_chips",
    material: "rock.igneous.volcanic",
    texture: "aphanitic",
  },
  {
    name: "Metamorphic outcrop (facies TBD)",
    owner: "sophie",
    nature: "thin_section",
    material: "rock.metamorphic",
    metamorphicFacies: "greenschist",
  },
  {
    name: "Sediment core top (unlogged)",
    owner: "pierre",
    nature: "sample_fragment",
    material: "sediment",
    type: "core",
  },
  {
    name: "Quarry block awaiting section",
    owner: "camille",
    nature: "hand_sample",
    material: "rock.igneous.plutonic",
    texture: "phaneritic",
    collectionMethod: "blasting",
  },
  {
    name: "Regional survey point",
    owner: "marie",
    nature: "multiple_sample",
    location: { region: { kind: "continent", country: "FR" } },
  },
  {
    name: "Cave locality note",
    owner: "theo",
    nature: "hand_sample",
    location: { localityName: "Vercors karst network" },
  },
  {
    name: "Point-only draft",
    owner: "theo",
    nature: "rock_powder",
    location: { position: point(3.0, 45.0) },
  },
  {
    name: "Partial elevation record",
    owner: "pierre",
    nature: "hand_sample",
    location: { position: point(2.0, 46.0, { min: -100 }) },
  },
  {
    name: "Unclassified mineral",
    owner: "theo",
    nature: "hand_sample",
    material: "mineral",
  },
  {
    name: "Coring campaign (unclassified)",
    owner: "marie",
    nature: "separated_materials",
    collectionMethod: "coring",
  },
  { name: "Legacy residue", owner: "jean", nature: "residue" },
  {
    name: "Rock of unknown type",
    owner: "sophie",
    nature: "hand_sample",
    material: "rock",
  },
  {
    name: "Schist draft (no facies yet)",
    owner: "pierre",
    nature: "thin_section",
    material: "rock.metamorphic.strongly_metamorphosed.schist",
  },
  {
    name: "Ash deposit draft",
    owner: "camille",
    nature: "rock_powder",
    material: "sediment.volcano_detritic.ash",
  },
  {
    name: "Fossil pending study",
    owner: "marie",
    nature: "hand_sample",
    material: "fossil",
  },
  {
    name: "Extraterrestrial sample (unclassified)",
    owner: "jean",
    nature: "hand_sample",
    material: "extraterrestrial_rock",
  },
  {
    name: "Area-location draft",
    owner: "sophie",
    nature: "hand_sample",
    location: { position: area(-1.0, 1.0, 44.0, 46.0) },
  },
  {
    name: "Locality-description draft",
    owner: "pierre",
    nature: "hand_sample",
    location: { localityDescription: "Near the old mine entrance" },
  },
  {
    name: "Clastic sedimentary draft",
    owner: "camille",
    nature: "rock_chips",
    material: "rock.sedimentary.clastic_sedimentary_rock",
  },
  {
    name: "Collection-date-only draft",
    owner: "marie",
    nature: "hand_sample",
    description: on("2024-03-03"),
  },
  {
    name: "Felsic pluton draft",
    owner: "jean",
    nature: "hand_sample",
    material: "rock.igneous.plutonic.felsic",
    collectionMethod: "manual",
  },
  {
    name: "Hydrothermal vent draft",
    owner: "sophie",
    nature: "hand_sample",
    material: "rock.hydrothermal",
  },
  {
    name: "Dredge haul draft",
    owner: "pierre",
    nature: "rock_chips",
    type: "dredge",
    material: "rock.igneous.volcanic.mafic",
  },
  {
    name: "Synthetic phase draft",
    owner: "camille",
    nature: "hand_sample",
    material: "synthetic_rock_mineral",
  },
  {
    name: "Sample series draft",
    owner: "marie",
    nature: "multiple_sample",
    type: "serie_of_sample",
  },
  {
    name: "Meteorite draft (chondrite?)",
    owner: "jean",
    nature: "sample_fragment",
    material: "extraterrestrial_rock.meteorites.chondrites",
  },
  {
    name: "Navigated point draft",
    owner: "sophie",
    nature: "hand_sample",
    location: {
      position: point(-20.0, 50.0),
      region: { kind: "ocean", oceanSea: "atlantic_ocean" },
      navigationType: "GPS",
    },
  },
  {
    name: "Inapplicable-nature draft",
    owner: "pierre",
    nature: "inapplicable",
    material: "mineral",
  },
  {
    name: "Draft awaiting everything",
    owner: "camille",
    nature: "thick_section",
  },
];

const demoId = (index: number): string =>
  `019f5b01-0000-7000-8000-${index.toString(16).padStart(12, "0")}`;

const RECENT_CONTEXT: SeedSample["scientificContext"] = {
  provenanceStatus: "recent_collection",
  funderOrganization: "02feahw73",
  researchProgramName: "Solid Earth Demo Survey",
  researchProgramChief: "Jean Dupont",
  researchStructure: ["02rx3b187"],
  collectorName: "Claire Martin",
};

const HISTORICAL_CONTEXT: SeedSample["scientificContext"] = {
  provenanceStatus: "historical_specimen",
  collectionCurator: "Paul Bernard",
  collectionOrigin: "scientific_expedition",
};

export const DEMO_SAMPLES: SeedSample[] = [...PUBLISHED, ...DRAFTS].map(
  (row, index) => {
    const id = demoId(index);
    const published = index < PUBLISHED.length;
    return {
      ...row,
      id,
      published,
      ...(published
        ? {
            igsn: generateIgsnSuffix(id),
            scientificContext:
              row.scientificContext ??
              (index % 2 === 0 ? RECENT_CONTEXT : HISTORICAL_CONTEXT),
          }
        : {}),
    };
  },
);
