import type { PublishedSample } from "#/domain/samples/sample-sections.tsx";

export const emptyAge = {
  numericAgeMin: null,
  numericAgeMax: null,
  numericAgeUnit: null,
  numericAgeYearsUnit: null,
  geologicalAgeMin: null,
  geologicalAgeMax: null,
  geologicalUnit: null,
};

export const publishedSample = (
  overrides: Partial<PublishedSample> = {},
): PublishedSample => ({
  id: "3f2504e0-4f89-41d3-9a0c-0305e82c3300",
  name: "Basalt 42",
  localId: null,
  localIdDescription: null,
  igsn: "0123456789ABCDEFGHJKMNPQRS",
  internalNumber: null,
  doiPrefix: "10.5072",
  institutionalOrganization: null,
  institutionalOsu: null,
  institutionalLaboratory: null,
  nature: "powder",
  type: null,
  material: null,
  texture: null,
  metamorphicFacies: null,
  metamorphicFabric: null,
  specificName: null,
  collectionMethod: null,
  collectionMethodDescription: null,
  description: null,
  condition: null,
  scientificContext: null,
  repository: null,
  geologicalContextDescription: null,
  physiographicEnvironment: null,
  syntheticDetails: null,
  location: null,
  age: null,
  relations: [],
  processSteps: [],
  attachments: [],
  security: null,
  existenceStatus: null,
  availabilityStatus: null,
  publicationYear: null,
  resourceType: null,
  economicInterestElements: [],
  economicResourceTypePrecision: null,
  economicDepositName: null,
  economicDepositDescription: null,
  manualGroups: [],
  parents: [],
  owner: null,
  status: "published" as const,
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
  ...overrides,
});
