/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TombstoneRouteImport } from './routes/tombstone'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LegalNoticeRouteImport } from './routes/legal-notice'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SamplesIgsnRouteImport } from './routes/samples/$igsn'

const TombstoneRoute = TombstoneRouteImport.update({
  id: '/tombstone',
  path: '/tombstone',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal-notice',
  path: '/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesIgsnRoute = SamplesIgsnRouteImport.update({
  id: '/samples/$igsn',
  path: '/samples/$igsn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/tombstone': typeof TombstoneRoute
  '/samples/$igsn': typeof SamplesIgsnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/tombstone': typeof TombstoneRoute
  '/samples/$igsn': typeof SamplesIgsnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/tombstone': typeof TombstoneRoute
  '/samples/$igsn': typeof SamplesIgsnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/legal-notice'
    | '/partners'
    | '/privacy-policy'
    | '/search'
    | '/terms-of-use'
    | '/tombstone'
    | '/samples/$igsn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/legal-notice'
    | '/partners'
    | '/privacy-policy'
    | '/search'
    | '/terms-of-use'
    | '/tombstone'
    | '/samples/$igsn'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/legal-notice'
    | '/partners'
    | '/privacy-policy'
    | '/search'
    | '/terms-of-use'
    | '/tombstone'
    | '/samples/$igsn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  LegalNoticeRoute: typeof LegalNoticeRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SearchRoute: typeof SearchRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  TombstoneRoute: typeof TombstoneRoute
  SamplesIgsnRoute: typeof SamplesIgsnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tombstone': {
      id: '/tombstone'
      path: '/tombstone'
      fullPath: '/tombstone'
      preLoaderRoute: typeof TombstoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-notice': {
      id: '/legal-notice'
      path: '/legal-notice'
      fullPath: '/legal-notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$igsn': {
      id: '/samples/$igsn'
      path: '/samples/$igsn'
      fullPath: '/samples/$igsn'
      preLoaderRoute: typeof SamplesIgsnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  LegalNoticeRoute: LegalNoticeRoute,
  PartnersRoute: PartnersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SearchRoute: SearchRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  TombstoneRoute: TombstoneRoute,
  SamplesIgsnRoute: SamplesIgsnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
