import { z } from "zod";

// Generated from a CSV export; do not edit by hand for bulk changes. Refresh
// with: pnpm --filter @projet-igsn/domain sync-institutions
export type Laboratory = {
  code: string;
  acronym: string;
  name: string;
  osu: string | null;
  organizationRors: readonly string[];
};

export const LABORATORIES: readonly Laboratory[] = [
  {
    code: "EA4038",
    acronym: "LGPM",
    name: "Laboratoire de Génie et Procédés des Matériaux",
    osu: null,
    organizationRors: ["03xjwb503"],
  },
  {
    code: "FR2424",
    acronym: "Roscoff",
    name: "Station biologique de Roscoff",
    osu: null,
    organizationRors: ["02feahw73", "02en5vm52"],
  },
  {
    code: "FR2952",
    acronym: "IPRA",
    name: "Institut Pluridisciplinaire de recherche appliquée en génie pétrolier",
    osu: null,
    organizationRors: ["02feahw73", "01frn9647"],
  },
  {
    code: "FR3724",
    acronym: "OOB",
    name: "Observatoire océanologique de Banyuls sur Mer",
    osu: null,
    organizationRors: ["02feahw73", "02en5vm52"],
  },
  {
    code: "FR3761",
    acronym: "IMEV",
    name: "Institut de la Mer de Villefranche",
    osu: null,
    organizationRors: ["02feahw73", "02en5vm52"],
  },
  {
    code: "FR636",
    acronym: "IPSL",
    name: "Institut Pierre-Simon-Laplace",
    osu: "OSU-Externe",
    organizationRors: [
      "02feahw73",
      "02en5vm52",
      "05f82e368",
      "05ggc9x40",
      "00jjx8s55",
      "04h1h0y33",
      "03mkjjy25",
      "05q3vnk25",
    ],
  },
  {
    code: "UAR 2050",
    acronym: "UNIDIA",
    name: "UNité d’Ingénierie et de Développements Instrumentaux pour l’Astrophysique",
    osu: "OBSPM",
    organizationRors: ["02feahw73", "029nkcm90"],
  },
  {
    code: "UAR3113",
    acronym: "IUEM",
    name: "Institut Universitaire Européen de la Mer",
    osu: null,
    organizationRors: ["02feahw73", "05q3vnk25"],
  },
  {
    code: "UAR3281",
    acronym: "OSUNA",
    name: "Unité Mixte de Service Observatoire des Sciences de l'Univers Nantes Atlantique",
    osu: "OSUNA",
    organizationRors: [
      "02feahw73",
      "03gnr7b55",
      "03x42jk29",
      "044jxhp58",
      "0175hh227",
    ],
  },
  {
    code: "UAR3470",
    acronym: "PYTHEAS",
    name: "Institut PYTHEAS",
    osu: "PYTHEAS",
    organizationRors: ["02feahw73", "035xkbk20", "003vg9w96"],
  },
  {
    code: "UAR704",
    acronym: "ORN",
    name: "Station de Radioastronomie de Nançay",
    osu: "OBSPM",
    organizationRors: ["02feahw73", "014zrew76", "029nkcm90"],
  },
  {
    code: "UMI3351",
    acronym: "IFAECI",
    name: "Institut Franco-Argentin d'études sur le climat et ses impacts",
    osu: null,
    organizationRors: ["02feahw73", "05q3vnk25"],
  },
  {
    code: "UMI3376",
    acronym: "TAKUVIK",
    name: "TAKUVIK",
    osu: null,
    organizationRors: ["02feahw73", "02en5vm52"],
  },
  {
    code: "UMI3386",
    acronym: "LFCA",
    name: "Laboratoire Franco-Chilien d'Astronomie",
    osu: null,
    organizationRors: ["02feahw73"],
  },
  {
    code: "UMR 8254",
    acronym: "LIRA",
    name: "Laboratoire d’Instrumentation et de Recherche en Astrophysique",
    osu: "OBSPM",
    organizationRors: ["02feahw73", "02en5vm52", "05f82e368", "029nkcm90"],
  },
  {
    code: "UMR 8262",
    acronym: "LUX",
    name: "Laboratoire d’étude de l’Univers et des phénomènes eXtrèmes",
    osu: "OBSPM",
    organizationRors: ["02feahw73", "02en5vm52", "029nkcm90"],
  },
  {
    code: "UMR1114",
    acronym: "EMMAH",
    name: "Laboratoire ( UMR mixte Université / INRA)",
    osu: null,
    organizationRors: ["003vg9w96"],
  },
  {
    code: "UMR3589",
    acronym: "CNRM",
    name: "Centre National de Recherches Météorologiques",
    osu: "OMP",
    organizationRors: ["02feahw73", "0233st365"],
  },
  {
    code: "UMR5001",
    acronym: "IGE",
    name: "Institut des Géosciences de l'Environnement",
    osu: "OSUG",
    organizationRors: ["02feahw73", "02rx3b187", "003vg9w96", "05q3vnk25"],
  },
  {
    code: "UMR5110",
    acronym: "CEFREM",
    name: "Centre de formation et de recherche sur les environnements méditerranéens",
    osu: "OMP",
    organizationRors: ["02feahw73", "03am2jy38"],
  },
  {
    code: "UMR5126",
    acronym: "CESBIO",
    name: "Centre d'études spatiales de la biosphère",
    osu: "OMP",
    organizationRors: ["02feahw73", "04h1h0y33", "01ahyrz84", "05q3vnk25"],
  },
  {
    code: "UMR5150",
    acronym: "LFC-R",
    name: "Laboratoire des fluides complexes et leurs réservoirs",
    osu: null,
    organizationRors: ["02feahw73", "01frn9647"],
  },
  {
    code: "UMR5193",
    acronym: "LISST",
    name: "LABORATOIRE INTERDISCIPLINAIRE SOLIDARITES, SOCIETES, TERRITOIRES",
    osu: null,
    organizationRors: ["02feahw73", "04ezk3x31"],
  },
  {
    code: "UMR5574",
    acronym: "CRAL",
    name: "Centre de Recherche Astrophysique de Lyon",
    osu: "OSUL",
    organizationRors: ["02feahw73", "029brtt94", "04zmssz18"],
  },
  {
    code: "UMR5194",
    acronym: "PACTE",
    name: "POLITIQUES PUBLIQUES, ACTION POLITIQUE, TERRITOIRES",
    osu: null,
    organizationRors: ["02feahw73", "02rx3b187"],
  },
  {
    code: "UMR5204",
    acronym: "EDYTEM",
    name: "ENVIRONNEMENTS, DYNAMIQUES ET TERRITOIRES DE LA MONTAGNE",
    osu: "OSUG",
    organizationRors: ["02feahw73", "04gqg1a07"],
  },
  {
    code: "UMR5205",
    acronym: "LIRIS",
    name: "Laboratoire d'Informatique en Image et Systèmes d'Information",
    osu: null,
    organizationRors: ["02feahw73", "029brtt94", "03rth4p18"],
  },
  {
    code: "UMR5213",
    acronym: "LAPLACE",
    name: "Laboratoire Plasma et Conversion d’Energie",
    osu: null,
    organizationRors: ["02feahw73", "01ahyrz84"],
  },
  {
    code: "UMR5243",
    acronym: "GEO MONTP",
    name: "Géosciences Montpellier",
    osu: "OREME",
    organizationRors: ["02feahw73", "051escj72", "02ryfmr77"],
  },
  {
    code: "UMR5256",
    acronym: "IRCELYON",
    name: "INSTITUT DE RECHERCHES SUR LA CATALYSE ET L'ENVIRONNEMENT DE LYON",
    osu: null,
    organizationRors: ["02feahw73", "029brtt94"],
  },
  {
    code: "UMR5263",
    acronym: "CLLE",
    name: "COGNITION, LANGUES, LANGAGE, ERGONOMIE",
    osu: null,
    organizationRors: ["02feahw73", "04ezk3x31"],
  },
  {
    code: "UMR5274",
    acronym: "IPAG",
    name: "Institut de Planétologie et d'Astrophysique de Grenoble",
    osu: "OSUG",
    organizationRors: ["02feahw73", "02rx3b187"],
  },
  {
    code: "UMR5275",
    acronym: "ISTerre",
    name: "Institut des Sciences de la Terre",
    osu: "OSUG",
    organizationRors: [
      "02feahw73",
      "02rx3b187",
      "03x42jk29",
      "04gqg1a07",
      "05q3vnk25",
    ],
  },
  {
    code: "UMR5276",
    acronym: "LGL-TPE",
    name: "Laboratoire de géologie de Lyon : Terre, Planètes, Environnement",
    osu: "OSUL",
    organizationRors: ["02feahw73", "029brtt94", "04yznqr36", "04zmssz18"],
  },
  {
    code: "UMR5277",
    acronym: "IRAP",
    name: "Institut de Recherche en Astrophysique et Planétologie",
    osu: "OMP",
    organizationRors: ["02feahw73", "04h1h0y33", "01ahyrz84"],
  },
  {
    code: "UMR5299",
    acronym: "LUPM",
    name: "Laboratoire Univers et Particules Montpellier",
    osu: "OREME",
    organizationRors: ["02feahw73", "051escj72"],
  },
  {
    code: "UMR5302",
    acronym: "RAPSODEE",
    name: "CENTRE DE RECHERCHE D'ALBI EN GENIE DES PROCEDES DES SOLIDES DIVISES, DE L'ENERGIE ET DE L'ENVIRONNEMENT",
    osu: null,
    organizationRors: ["02feahw73"],
  },
  {
    code: "UMR5318",
    acronym: "CECI",
    name: "Climat, Environnement, Couplages et Incertitudes",
    osu: "OMP",
    organizationRors: ["02feahw73"],
  },
  {
    code: "UMR5560",
    acronym: "LAERO",
    name: "Laboratoire d'aérologie",
    osu: "OMP",
    organizationRors: ["02feahw73", "01ahyrz84"],
  },
  {
    code: "UMR5563",
    acronym: "GET",
    name: "Géosciences environnement Toulouse",
    osu: "OMP",
    organizationRors: ["02feahw73", "01ahyrz84", "05q3vnk25"],
  },
  {
    code: "UMR5566",
    acronym: "LEGOS",
    name: "Laboratoire d'études en Géophysique et océanographie spatiales",
    osu: "OMP",
    organizationRors: ["02feahw73", "04h1h0y33", "01ahyrz84", "05q3vnk25"],
  },
  {
    code: "UMR5569",
    acronym: "HSM",
    name: "Hydrosciences Montpellier",
    osu: "OREME",
    organizationRors: ["02feahw73", "051escj72", "05q3vnk25"],
  },
  {
    code: "UMR5602",
    acronym: "GEODE",
    name: "GEOGRAPHIE DE L'ENVIRONNEMENT",
    osu: null,
    organizationRors: ["02feahw73", "04ezk3x31"],
  },
  {
    code: "UMR5804",
    acronym: "LAB",
    name: "Laboratoire d'astrophysique de Bordeaux",
    osu: "OASU",
    organizationRors: ["02feahw73", "057qpr032"],
  },
  {
    code: "UMR8190",
    acronym: "LATMOS",
    name: 'Laboratoire"Atmosphères, Milieux, Observations Spatiales"',
    osu: "OVSQ",
    organizationRors: ["02feahw73", "02en5vm52", "03mkjjy25"],
  },
  {
    code: "UMR5805",
    acronym: "EPOC",
    name: "Environnements et paléoenvironnements océaniques et continentaux",
    osu: "OASU",
    organizationRors: ["02feahw73", "057qpr032"],
  },
  {
    code: "UAR3116",
    acronym: "OSUC",
    name: "Observatoire des Sciences de l'Univers en région Centre",
    osu: "OSUC",
    organizationRors: ["02feahw73", "014zrew76"],
  },
  {
    code: "UMR6016",
    acronym: "LAMP",
    name: "Laboratoire de météorologie physique",
    osu: "OPGC",
    organizationRors: ["02feahw73", "01a8ajp46"],
  },
  {
    code: "UMR6112",
    acronym: "LPG",
    name: "Laboratoire de Planétologie et Géosciences",
    osu: "OSUNA",
    organizationRors: ["02feahw73", "01mtcc283", "03gnr7b55", "04yrqp957"],
  },
  {
    code: "UMR6118",
    acronym: "GeoRen",
    name: "Géosciences Rennes",
    osu: "OSERen",
    organizationRors: ["02feahw73", "015m7wh34"],
  },
  {
    code: "UMR6143",
    acronym: "M2C",
    name: "Laboratoire de Morphodynamique continentale et côtière",
    osu: "Ecce Terra",
    organizationRors: ["02feahw73", "051kpcy16", "03nhjew95"],
  },
  {
    code: "UMR6164",
    acronym: "IETR",
    name: "INSTITUT D'ELECTRONIQUE ET DE TELECOMMUNICATION DE RENNES",
    osu: "OSERen",
    organizationRors: ["02feahw73", "03gnr7b55", "015m7wh34", "03rxtdc22"],
  },
  {
    code: "UMR6213",
    acronym: "UTINAM",
    name: "Institut UTINAM (Univers, Transport, Interfaces Nanostructures, Atmosphère et Environnement, Molécules)",
    osu: "THETA",
    organizationRors: ["02feahw73", "03pcc9z86"],
  },
  {
    code: "UMR6249",
    acronym: "CHRONO-ENV",
    name: "Chrono-environnement",
    osu: "THETA",
    organizationRors: ["02feahw73", "03pcc9z86"],
  },
  {
    code: "UMR6251",
    acronym: "IPR",
    name: "Institut de Physique de Rennes",
    osu: "OSERen",
    organizationRors: ["02feahw73", "015m7wh34"],
  },
  {
    code: "UMR6266",
    acronym: "IDEES",
    name: "Identité et Différenciation de l'Espace, de l'Environnement et des Sociétés",
    osu: null,
    organizationRors: ["02feahw73", "05v509s40", "051kpcy16", "03nhjew95"],
  },
  {
    code: "UMR6294",
    acronym: "LOMC",
    name: "Laboratoire d'ondes et milieux complexes",
    osu: null,
    organizationRors: ["02feahw73", "05v509s40"],
  },
  {
    code: "UMR6502",
    acronym: "IMN",
    name: "INSTITUT DES MATERIAUX JEAN ROUXEL",
    osu: null,
    organizationRors: ["02feahw73", "03gnr7b55"],
  },
  {
    code: "UMR6523",
    acronym: "LOPS",
    name: "LABORATOIRE D'OCEANOGRAPHIE PHYSIQUE ET SPATIALE",
    osu: "IUEM",
    organizationRors: ["02feahw73", "044jxhp58", "05q3vnk25"],
  },
  {
    code: "UMR6524",
    acronym: "LMV",
    name: "Laboratoire Magmas et volcans",
    osu: "OPGC",
    organizationRors: ["02feahw73", "01a8ajp46", "04yznqr36", "05q3vnk25"],
  },
  {
    code: "UMR6538",
    acronym: "GEO-OCEAN",
    name: "Laboratoire Géosciences Océan",
    osu: "IUEM",
    organizationRors: ["02feahw73", "044jxhp58"],
  },
  {
    code: "UMR6539",
    acronym: "LEMAR",
    name: "Laboratoire des sciences de l'environnement marin",
    osu: "IUEM",
    organizationRors: ["02feahw73", "044jxhp58", "05q3vnk25"],
  },
  {
    code: "UMR6553",
    acronym: "ECOBIO",
    name: "Ecosystèmes, biodiversité, évolution",
    osu: "OSERen",
    organizationRors: ["02feahw73", "015m7wh34"],
  },
  {
    code: "UMR6554",
    acronym: "IDEES CAEN",
    name: "IDEES CAEN",
    osu: null,
    organizationRors: ["02feahw73", "051kpcy16", "05v509s40", "01m84wm78"],
  },
  {
    code: "UMR7093",
    acronym: "LOV",
    name: "Laboratoire d'océanographie de Villefranche",
    osu: "STAMAR",
    organizationRors: ["02feahw73", "02en5vm52"],
  },
  {
    code: "UMR7095",
    acronym: "IAP",
    name: "Institut d'Astrophysique de Paris",
    osu: "IAP",
    organizationRors: ["02feahw73", "02en5vm52"],
  },
  {
    code: "UMR7144",
    acronym: "AD2M",
    name: "Adaptation et diversité en milieu marin",
    osu: "STAMAR",
    organizationRors: ["02feahw73", "02en5vm52"],
  },
  {
    code: "UMR7154",
    acronym: "IPGP",
    name: "Institut de physique du globe de Paris",
    osu: "IPGP",
    organizationRors: ["02feahw73", "05f82e368", "004gzqz66"],
  },
  {
    code: "UMR7158",
    acronym: "AIM",
    name: "Astrophysique, Instrumentation et Modélisation, de Paris-Saclay",
    osu: "OSUPS",
    organizationRors: ["02feahw73", "05f82e368", "00jjx8s55"],
  },
  {
    code: "UMR7159",
    acronym: "LOCEAN",
    name: "Laboratoire d'Océanographie et du Climat : Expérimentations et Approches Numériques",
    osu: "OSU-Externe",
    organizationRors: ["02feahw73", "02en5vm52", "05q3vnk25", "03wkt5x30"],
  },
  {
    code: "UMR7164",
    acronym: "APC",
    name: "Astroparticule et Cosmologie",
    osu: null,
    organizationRors: ["02feahw73", "05f82e368", "00jjx8s55", "029nkcm90"],
  },
  {
    code: "UMR7193",
    acronym: "iSTeP",
    name: "Institut des Sciences de la Terre Paris",
    osu: "Ecce Terra",
    organizationRors: ["02feahw73", "043htjv09", "02en5vm52"],
  },
  {
    code: "UMR7202",
    acronym: "LMCM",
    name: "Laboratoire de Minéralogie et Cosmochimie du Muséum",
    osu: null,
    organizationRors: ["03wkt5x30"],
  },
  {
    code: "UMR7208",
    acronym: "BOREA",
    name: "Biologie des organismes et écosystèmes aquatiques",
    osu: "Ecce Terra",
    organizationRors: [
      "02feahw73",
      "02en5vm52",
      "05q3vnk25",
      "03wkt5x30",
      "02ryfmr77",
    ],
  },
  {
    code: "UMR7250",
    acronym: "ARTEMIS",
    name: "Astrophysique Relativiste, Théories, Expériences, Métrologie, Instrumentation, Signaux",
    osu: "OCA",
    organizationRors: ["02feahw73", "019tgvf94", "039fj2469"],
  },
  {
    code: "UMR7266",
    acronym: "LIENS",
    name: "Littoral, Environnement et Sociétés",
    osu: "OASU",
    organizationRors: ["02feahw73", "04mv1z119"],
  },
  {
    code: "UMR7285",
    acronym: "IC2MP",
    name: "Institut de Chimie des Milieux et des Matériaux de Poitiers",
    osu: null,
    organizationRors: ["02feahw73", "04xhy8q59"],
  },
  {
    code: "UMR7293",
    acronym: "Lagrange",
    name: "Laboratoire Joseph-Louis Lagrange",
    osu: "OCA",
    organizationRors: ["02feahw73", "019tgvf94", "039fj2469"],
  },
  {
    code: "UMR7294",
    acronym: "MIO",
    name: "Institut Méditerranéen d'Océanographie",
    osu: "PYTHEAS",
    organizationRors: ["02feahw73", "035xkbk20", "02m9kbe37", "05q3vnk25"],
  },
  {
    code: "UMR7300",
    acronym: "ESPACE",
    name: "Etudes des structures, des processus d'adaptation et des changements de l'espace",
    osu: null,
    organizationRors: ["02feahw73", "035xkbk20", "019tgvf94"],
  },
  {
    code: "UMR7326",
    acronym: "LAM",
    name: "Laboratoire d'Astrophysique de Marseille",
    osu: "PYTHEAS",
    organizationRors: ["02feahw73", "035xkbk20", "04h1h0y33"],
  },
  {
    code: "UMR7327",
    acronym: "ISTO",
    name: "Institut des Sciences de la Terre d'Orléans",
    osu: "OSUC",
    organizationRors: ["02feahw73", "05hnb7x64", "014zrew76"],
  },
  {
    code: "UMR7328",
    acronym: "LPC2E",
    name: "Laboratoire de physique et chimie de l'environnement et de l'Espace",
    osu: "OSUC",
    organizationRors: ["02feahw73", "04h1h0y33", "014zrew76"],
  },
  {
    code: "UMR7329",
    acronym: "GEOAZUR",
    name: "Géoazur",
    osu: "OCA",
    organizationRors: ["02feahw73", "019tgvf94", "05q3vnk25", "039fj2469"],
  },
  {
    code: "UMR7330",
    acronym: "CEREGE",
    name: "Centre européen de recherche et d'enseignement de géosciences de l'environnement",
    osu: "PYTHEAS",
    organizationRors: ["02feahw73", "035xkbk20", "003vg9w96", "05q3vnk25"],
  },
  {
    code: "UMR7331",
    acronym: "GSMA",
    name: "Groupe de spectrométrie moléculaire et atmosphérique",
    osu: null,
    organizationRors: ["02feahw73", "03hypw319"],
  },
  {
    code: "UMR7358",
    acronym: "CRPG",
    name: "Centre de recherches pétrographiques et géochimiques",
    osu: "OTELo",
    organizationRors: ["02feahw73", "04vfs2w97"],
  },
  {
    code: "UMR7359",
    acronym: "GEORESSOURCES",
    name: "GéoRessources",
    osu: "OTELo",
    organizationRors: ["02feahw73", "04vfs2w97"],
  },
  {
    code: "UMR7360",
    acronym: "LIEC",
    name: "Laboratoire Interdisciplinaire des Environnements continentaux",
    osu: "OTELo",
    organizationRors: ["02feahw73", "04vfs2w97"],
  },
  {
    code: "UMR7372",
    acronym: "CEBC",
    name: "Centre d'études biologiques de Chizé",
    osu: null,
    organizationRors: ["02feahw73", "04mv1z119"],
  },
  {
    code: "UMR7550",
    acronym: "OBAS",
    name: "Observatoire astronomique de Strasbourg",
    osu: "ObAS",
    organizationRors: ["02feahw73", "00pg6eq24"],
  },
  {
    code: "UMR7583",
    acronym: "LISA",
    name: "Laboratoire inter-universitaire des systèmes atmosphèriques",
    osu: "EFLUVE",
    organizationRors: ["02feahw73", "05f82e368", "05ggc9x40"],
  },
  {
    code: "UMR7590",
    acronym: "IMPMC",
    name: "Institut de minéralogie et de physique des milieux condensés",
    osu: "Ecce Terra",
    organizationRors: ["02feahw73", "02en5vm52", "03wkt5x30"],
  },
  {
    code: "UMR7608",
    acronym: "FAST",
    name: "Fluides, Automatique et Systèmes Thermiques",
    osu: null,
    organizationRors: ["02feahw73", "03xjwb503"],
  },
  {
    code: "UMR7621",
    acronym: "LOMIC",
    name: "Laboratoire d'océanographie microbienne",
    osu: "STAMAR",
    organizationRors: ["02feahw73", "02en5vm52"],
  },
  {
    code: "UMR7648",
    acronym: "LPP",
    name: "Laboratoire de physique des plasmas",
    osu: null,
    organizationRors: ["02feahw73", "02en5vm52", "03xjwb503", "029nkcm90"],
  },
  {
    code: "UMR8023",
    acronym: "LPENS",
    name: "Laboratoire de Physique de l’École normale supérieure",
    osu: null,
    organizationRors: ["02feahw73", "02en5vm52", "05f82e368"],
  },
  {
    code: "UMR8105",
    acronym: "LACy",
    name: "Laboratoire de l'Atmosphère et des Cyclones",
    osu: "OSU-Réunion",
    organizationRors: ["02feahw73", "0233st365"],
  },
  {
    code: "UMR8109",
    acronym: "LIRA",
    name: "Laboratoire d'Etudes Spatiales et d'Instrumentation en Astrophysique",
    osu: "OBSPM",
    organizationRors: [
      "02feahw73",
      "02en5vm52",
      "05f82e368",
      "013cjyk83",
      "029nkcm90",
    ],
  },
  {
    code: "UMR8148",
    acronym: "GEOPS",
    name: "Géosciences Paris-Sud",
    osu: "OSUPS",
    organizationRors: ["02feahw73", "03xjwb503"],
  },
  {
    code: "UMR8187",
    acronym: "LOG",
    name: "Laboratoire d'océanologie et de géosciences",
    osu: null,
    organizationRors: ["02feahw73", "02kzqn938", "02gdcg342"],
  },
  {
    code: "UMR8212",
    acronym: "LSCE",
    name: "Laboratoire des sciences du climat et de l'environnement",
    osu: "OVSQ",
    organizationRors: ["02feahw73", "00jjx8s55", "03mkjjy25"],
  },
  {
    code: "UMR8217",
    acronym: "Géosystèmes",
    name: "Géosystèmes",
    osu: null,
    organizationRors: ["02feahw73", "02kzqn938", "01gyxrk03"],
  },
  {
    code: "UMR8247",
    acronym: "IRCP",
    name: "Institut de Recherche de Chimie Paris",
    osu: null,
    organizationRors: ["02feahw73"],
  },
  {
    code: "UMR8255",
    acronym: "LTE",
    name: "Laboratoire Temps Espace",
    osu: "OBSPM",
    organizationRors: ["02feahw73", "02en5vm52", "02kzqn938", "029nkcm90"],
  },
  {
    code: "UMR8518",
    acronym: "LOA",
    name: "Laboratoire d'optique atmosphèrique",
    osu: null,
    organizationRors: ["02feahw73", "02kzqn938"],
  },
  {
    code: "UMR8538",
    acronym: "LABORATOIRE DE GÉOLOGIE DE L'ENS",
    name: "Laboratoire de Géologie de l'Ecole Normale Supérieure",
    osu: "Ecce Terra",
    organizationRors: ["02feahw73"],
  },
  {
    code: "UMR8539",
    acronym: "LMD",
    name: "Laboratoire de météorologie dynamique",
    osu: "Ecce Terra",
    organizationRors: ["02feahw73", "02en5vm52"],
  },
  {
    code: "UMR8617",
    acronym: "IAS",
    name: "Institut d'astrophysique spatiale",
    osu: "OSUPS",
    organizationRors: ["02feahw73", "03xjwb503"],
  },
  {
    code: "UMR9189",
    acronym: "CRIStAL",
    name: "Centre de Recherche en Informatique, Signal, et Automatique de Lille",
    osu: null,
    organizationRors: ["02feahw73", "02kzqn938"],
  },
  {
    code: "UMR9220",
    acronym: "ENTROPIE",
    name: "Ecologie Marine Tropicale des Océans Pacifique et Indien",
    osu: "OSU-Réunion",
    organizationRors: ["044jxhp58", "05q3vnk25"],
  },
  {
    code: "UAR2201",
    acronym: "OP",
    name: "Observatoire de Paris",
    osu: null,
    organizationRors: ["02feahw73", "013cjyk83", "029nkcm90"],
  },
  {
    code: "UAR2202",
    acronym: "OCA",
    name: "Observatoire de la Côte d'Azur",
    osu: "OCA",
    organizationRors: ["02feahw73", "019tgvf94", "039fj2469"],
  },
  {
    code: "UAR2567",
    acronym: "OASU",
    name: "Observatoire aquitain des sciences de l'univers",
    osu: "OASU",
    organizationRors: ["02feahw73", "04mv1z119", "057qpr032", "003vg9w96"],
  },
  {
    code: "UAR2572",
    acronym: "LMC14",
    name: "Laboratoire de mesure du carbone 14",
    osu: null,
    organizationRors: ["02feahw73", "00jjx8s55", "05q3vnk25"],
  },
  {
    code: "UAR2859",
    acronym: "SAFIRE",
    name: "Service des Avions Français Instrumentés pour la Recherche en Environnement",
    osu: null,
    organizationRors: ["02feahw73", "04h1h0y33", "0233st365"],
  },
  {
    code: "UAR2877",
    acronym: "ICARE",
    name: "ICARE",
    osu: null,
    organizationRors: ["02feahw73", "04h1h0y33", "02kzqn938"],
  },
  {
    code: "UAR3245",
    acronym: "THETA",
    name: "Terre-Homme-Environnement-Temps-Astronomie",
    osu: "THETA",
    organizationRors: ["02feahw73", "03k1bsr36", "03pcc9z86"],
  },
  {
    code: "UAR3282",
    acronym: "OREME",
    name: "Observatoire de REcherche Méditerranéen de l'Environnement",
    osu: "OREME",
    organizationRors: ["02feahw73", "051escj72", "003vg9w96", "05q3vnk25"],
  },
  {
    code: "UAR3342",
    acronym: "OVSQ",
    name: "Unité mixte de service de l'OSU-OVSQ",
    osu: "OVSQ",
    organizationRors: ["02feahw73", "03mkjjy25"],
  },
  {
    code: "UAR3343",
    acronym: "OSERen",
    name: "Unité mixte de service pour l'Observatoire de Rennes",
    osu: "OSERen",
    organizationRors: ["02feahw73", "01m84wm78", "015m7wh34"],
  },
  {
    code: "UAR3365",
    acronym: "OSU-Réunion",
    name: "Unité mixte de service de l'OSU de la Réunion",
    osu: "OSU-Réunion",
    organizationRors: ["02feahw73", "05q3vnk25", "0233st365"],
  },
  {
    code: "UAR3454",
    acronym: "IPGP",
    name: "Unité mixte de service de de l'Institut de Physique du Globe de Paris",
    osu: "IPGP",
    organizationRors: ["02feahw73", "004gzqz66"],
  },
  {
    code: "UAR3455",
    acronym: "Ecce Terra",
    name: "Observatoire des sciences de l'Univers Ecce-Terra",
    osu: "Ecce Terra",
    organizationRors: [
      "02feahw73",
      "02en5vm52",
      "003vg9w96",
      "05q3vnk25",
      "03wkt5x30",
    ],
  },
  {
    code: "UAR3538",
    acronym: "LSBB",
    name: "Laboratoire sous terrain à Bas Bruit",
    osu: null,
    organizationRors: ["02feahw73"],
  },
  {
    code: "UAR3562",
    acronym: "OTELo",
    name: "Observatoire Terre et Environnement de Lorraine",
    osu: "OTELo",
    organizationRors: ["02feahw73", "04vfs2w97"],
  },
  {
    code: "UAR3563",
    acronym: "EFLUVE",
    name: 'Unité mixte de service"Enveloppes fluides : de la ville à l\'exobiologie"',
    osu: "EFLUVE",
    organizationRors: ["02feahw73", "05f82e368", "05ggc9x40"],
  },
  {
    code: "UAR3721",
    acronym: "OSUL",
    name: "Observatoire de Lyon",
    osu: "OSUL",
    organizationRors: ["02feahw73", "029brtt94", "04zmssz18"],
  },
  {
    code: "UAR830",
    acronym: "EOST",
    name: "Ecole et Observatoire des sciences de la Terre de Strasbourg",
    osu: "EOST",
    organizationRors: ["02feahw73", "00pg6eq24"],
  },
  {
    code: "UAR831",
    acronym: "OMP",
    name: "Observatoire midi-Pyrénées",
    osu: "OMP",
    organizationRors: [
      "02feahw73",
      "04h1h0y33",
      "01ahyrz84",
      "05q3vnk25",
      "0233st365",
    ],
  },
  {
    code: "UAR832",
    acronym: "OSUG",
    name: "Observatoire des Sciences de l'Univers de Grenoble",
    osu: "OSUG",
    organizationRors: ["02feahw73", "02rx3b187", "003vg9w96", "05q3vnk25"],
  },
  {
    code: "UAR833",
    acronym: "OPGC",
    name: "Observatoire de physique du globe de Clermont-Ferrand",
    osu: "OPGC",
    organizationRors: ["02feahw73", "01a8ajp46"],
  },
  {
    code: "UPR3079",
    acronym: "CEMHTI",
    name: "Conditions Extrêmes et Matériaux : Haute température et Irradiation",
    osu: null,
    organizationRors: ["02feahw73"],
  },
  {
    code: "UPR3266",
    acronym: "GANIL",
    name: "Grand accélérateur national d'ions lourds",
    osu: null,
    organizationRors: ["02feahw73", "00jjx8s55"],
  },
  {
    code: "UPR3346",
    acronym: "Pprime",
    name: "Institut P' : Recherche et Ingénierie en Matériaux, Mécanique et Energétique",
    osu: null,
    organizationRors: ["02feahw73", "04xhy8q59"],
  },
  {
    code: "UPR4301",
    acronym: "CBM",
    name: "Centre de biophysique moléculaire",
    osu: "OSUC",
    organizationRors: ["02feahw73"],
  },
  {
    code: "UPR8641",
    acronym: "CRPP",
    name: "CENTRE DE RECHERCHE PAUL PASCAL",
    osu: null,
    organizationRors: ["02feahw73", "057qpr032"],
  },
  {
    code: "UPS2074",
    acronym: "IRAM",
    name: "Institut de Radio Astronomie Millimétrique",
    osu: "OVSQ",
    organizationRors: ["02feahw73"],
  },
  {
    code: "UPS2776",
    acronym: "POUCHET",
    name: "POUCHET",
    osu: null,
    organizationRors: ["02feahw73"],
  },
  {
    code: "UPS2928",
    acronym: "IPEV",
    name: "Institut Polaire Français Paul Emile Victor",
    osu: null,
    organizationRors: ["02feahw73"],
  },
  {
    code: "UPS855",
    acronym: "DT-INSU",
    name: "Division technique de l'INSU",
    osu: null,
    organizationRors: ["02feahw73"],
  },
  {
    code: "USR3278",
    acronym: "CRIOBE",
    name: "Centre de recherche insulaire et observatoire de l'environnement",
    osu: null,
    organizationRors: ["02feahw73", "03am2jy38"],
  },
];

// ponytail: format only like osuCodeSchema, membership enforced by the cascade validator
export const laboratoryCodeSchema = z.string().trim().min(1);
